### ISSUE TITLE
 Migrate to Go module and Use offficial compiler for cross-compiling

### ISSUE THREAD

**Issue by QuantumGhost** [git-hooks/git-hooks#27]
Since Module has become the official dependency manager for Golang, and Golang has provided cross-compiling ability in the official compiler, there's no need to rely on third party tools like Godeps or gox.
Is there any plan to remove Gox and Godeps? If I submit a PR about this, would it be accepted?

**Comment by CatTail** [comment]
Hey @QuantumGhost, I don't have a plan to remove Gox and Godeps, but PRs are welcome :)

**Comment by QuantumGhost** [comment]
Ok, I'll send a PR once I have finished cleanup.

**Comment by QuantumGhost** [comment]
resolved in #28

**Comment by QuantumGhost** [comment]
I got errors below after running `go get -u github.com/git-hooks/git-hooks`

```
❯ go get -u github.com/git-hooks/git-hooks
# github.com/git-hooks/git-hooks
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:27:13: cannot use bind(list) (type func(*cli.Context)) as type cli.ActionFunc in assignment
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:31:4: unknown field 'ShortName' in struct literal of type cli.Command
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:33:4: cannot use bind(install, true) (type func(*cli.Context)) as type cli.ActionFunc in field value
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:38:4: cannot use bind(uninstall) (type func(*cli.Context)) as type cli.ActionFunc in field value
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:43:4: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in field value
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:54:4: cannot use bind(uninstallGlobal) (type func(*cli.Context)) as type cli.ActionFunc in field value
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:59:4: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in field value
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:72:4: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in field value
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:73:15: cannot use c.Args() (type cli.Args) as type []string in argument to run
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:78:4: unknown field 'ShortName' in struct literal of type cli.Command
/Users/momo/.cache/go/src/github.com/git-hooks/git-hooks/cli.go:78:4: too many errors
```

I believe I have fixed this issue in my PR #28, so I guess @CatTail you need to tag the master branch in order to make git-hooks go gettable.

**Comment by CatTail** [comment]
@QuantumGhost I tag the latest master with v1.3.0, but the error is still there.

**Comment by QuantumGhost** [comment]
It seems that `go get -u -v github.com/git-hooks/git-hooks` works for me now. I guess there are some cache issues.

logs:

```
❯  go get -u -v github.com/git-hooks/git-hooks
go: finding github.com/git-hooks/git-hooks v1.3.0
go: downloading github.com/git-hooks/git-hooks v1.3.0
go: extracting github.com/git-hooks/git-hooks v1.3.0
go: downloading github.com/cattail/go-exclude v0.0.0-20141118090525-7e63167c2dab
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/wsxiaoys/terminal v0.0.0-20160513160801-0940f3fc43a0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading github.com/urfave/cli v1.22.1
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/blang/semver v3.5.1+incompatible
go: extracting github.com/cattail/go-exclude v0.0.0-20141118090525-7e63167c2dab
go: extracting github.com/wsxiaoys/terminal v0.0.0-20160513160801-0940f3fc43a0
go: extracting github.com/urfave/cli v1.22.1
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: extracting github.com/google/go-github v17.0.0+incompatible
go: extracting github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/google/go-querystring v1.0.0
go: extracting github.com/google/go-querystring v1.0.0
go: extracting github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: extracting github.com/shurcooL/sanitized_anchor_name v1.0.0
go: finding github.com/google/go-querystring v1.0.0
go: finding github.com/google/go-github v17.0.0+incompatible
go: finding github.com/mitchellh/go-homedir v1.1.0
go: finding github.com/shurcooL/sanitized_anchor_name v1.0.0
go: finding github.com/russross/blackfriday/v2 v2.0.1
go: finding github.com/cpuguy83/go-md2man/v2 v2.0.0
go: finding github.com/urfave/cli v1.22.2
go: finding github.com/blang/semver v3.5.1+incompatible
go: finding github.com/wsxiaoys/terminal latest
go: finding github.com/cattail/go-exclude latest
go: downloading github.com/urfave/cli v1.22.2
go: extracting github.com/urfave/cli v1.22.2
github.com/shurcooL/sanitized_anchor_name
github.com/cattail/go-exclude
github.com/blang/semver
github.com/google/go-querystring/query
github.com/mitchellh/go-homedir
github.com/russross/blackfriday/v2
github.com/wsxiaoys/terminal/color
github.com/google/go-github/github
github.com/cpuguy83/go-md2man/v2/md2man
github.com/urfave/cli
github.com/git-hooks/git-hooks
```

**Comment by QuantumGhost** [comment]
After some digging, I finally figured out that I need to set `export GO111MODULE=on` to use `go get -u -v github.com/git-hooks/git-hooks`.

**Comment by CatTail** [comment]
@QuantumGhost 👍
